import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/app/components/NavBar";
import { SessionProvider } from "next-auth/react";
import AuthLayout from "@/app/components/AuthLayout";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter"; // or `v14-appRouter` if you are using Next.js v14

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lecture Chatbot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={inter.className + " flex flex-col h-[100vh] max-h-[100vh]"}
      >
        <AppRouterCacheProvider>
          <AuthLayout>
            <NavBar />
            {children}
          </AuthLayout>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
